import type { Circuit, CircuitOpportunity } from '../types/circuit.types'
import type { RegionMetric, PulseEvolution } from '../types/metrics.types'
import type { Resource } from '../types/resource.types'
import type { School } from '../types/school.types'
import type { Show } from '../types/show.types'

export const shows: Show[] = [
  {
    id: 'peleja-riso',
    name: 'A Peleja do Riso',
    group: 'Mamulengo Flor do Sertão',
    originCity: 'Arcoverde',
    synopsis:
      'Brincadeira de mamulengo contemporânea sobre uma trupe que atravessa o sertão levando feira, música e histórias de esperteza popular.',
    languages: ['Mamulengo', 'Cultura Popular'],
    durationMinutes: 55,
    minAge: 6,
    minFee: 6500,
    hasWorkshop: true,
    workshopDescription: 'Oficina de construção de bonecos de luva para estudantes e educadores.',
    presentations: 18,
    availability: ['2026-06-04', '2026-06-05', '2026-06-06', '2026-06-07'],
    rider: {
      stageWidth: 6,
      stageDepth: 4,
      sound: 'PA médio, 4 canais, 2 microfones sem fio',
      light: '12 refletores LED, luz frontal quente',
      powerKw: 6,
      generator: false,
      cargoKg: 180,
      cargoM3: 2.4,
      setupHours: 2,
      technicians: 1,
    },
  },
  {
    id: 'corpos-barro',
    name: 'Corpos de Barro',
    group: 'Cia Trapiá de Dança',
    originCity: 'Caruaru',
    synopsis: 'Dança para palco e espaços alternativos inspirada no barro, na feira e nos deslocamentos do Agreste.',
    languages: ['Dança'],
    durationMinutes: 45,
    minAge: 10,
    minFee: 8200,
    hasWorkshop: true,
    workshopDescription: 'Ação formativa de corpo, chão e memória para jovens.',
    presentations: 11,
    availability: ['2026-06-12', '2026-06-13', '2026-06-14'],
    rider: {
      stageWidth: 8,
      stageDepth: 6,
      sound: 'PA estéreo, entrada P2 e mesa simples',
      light: 'Mapa básico com contraluz e laterais',
      powerKw: 8,
      generator: false,
      cargoKg: 90,
      cargoM3: 1.2,
      setupHours: 3,
      technicians: 2,
    },
  },
  {
    id: 'lonas-abertas',
    name: 'Lonas Abertas',
    group: 'Coletivo Circo na Mata',
    originCity: 'Goiana',
    synopsis: 'Espetáculo de circo de rua com números de equilíbrio, comicidade física e participação do público.',
    languages: ['Circo'],
    durationMinutes: 50,
    minAge: 0,
    minFee: 5400,
    hasWorkshop: false,
    presentations: 9,
    availability: ['2026-06-20', '2026-06-21'],
    rider: {
      stageWidth: 10,
      stageDepth: 10,
      sound: 'Caixa amplificada ou PA de pequeno porte',
      light: 'Autônomo para dia; 6 refletores para noite',
      powerKw: 4,
      generator: true,
      cargoKg: 260,
      cargoM3: 5.6,
      setupHours: 2,
      technicians: 1,
    },
  },
  {
    id: 'rio-dentro',
    name: 'Rio de Dentro',
    group: 'Núcleo São Francisco de Música',
    originCity: 'Petrolina',
    synopsis: 'Concerto cênico com canções autorais, projeções e narrativas sobre travessias no Sertão do São Francisco.',
    languages: ['Música', 'Teatro'],
    durationMinutes: 70,
    minAge: 12,
    minFee: 9800,
    hasWorkshop: true,
    workshopDescription: 'Roda de criação sonora com estudantes.',
    presentations: 7,
    availability: ['2026-07-02', '2026-07-03'],
    rider: {
      stageWidth: 8,
      stageDepth: 5,
      sound: '16 canais, 4 retornos, DI para baixo e violão',
      light: 'Mesa DMX, 18 refletores, projetor',
      powerKw: 12,
      generator: false,
      cargoKg: 340,
      cargoM3: 4,
      setupHours: 4,
      technicians: 3,
    },
  },
]

export const circuits: Circuit[] = [
  {
    id: 'circuito-mamulengo',
    name: 'Circuito Bonecos Acesos',
    status: 'IN_PROGRESS',
    region: 'Agreste e Sertão',
    showId: 'peleja-riso',
    showName: 'A Peleja do Riso',
    group: 'Mamulengo Flor do Sertão',
    startDate: '2026-05-20',
    endDate: '2026-05-26',
    contractors: ['Sesc Caruaru', 'Sesc Arcoverde', 'Sesc Recife', 'Prefeitura de Olinda'],
    totalCost: 41200,
    confirmedStops: 4,
    costShares: [
      { contractor: 'Sesc Caruaru', value: 11800, color: '#D4A017' },
      { contractor: 'Sesc Arcoverde', value: 9800, color: '#B85C38' },
      { contractor: 'Sesc Recife', value: 11200, color: '#F2C94C' },
      { contractor: 'Olinda', value: 8400, color: '#0D0D0D' },
    ],
    stops: [
      {
        id: 'stop-caruaru',
        municipalityId: 'caruaru',
        municipality: 'Caruaru',
        venue: 'Sesc Caruaru',
        date: '2026-05-20',
        time: '19:30',
        status: 'confirmed',
        coords: { lat: -8.2846, lng: -35.9699 },
      },
      {
        id: 'stop-arcoverde',
        municipalityId: 'arcoverde',
        municipality: 'Arcoverde',
        venue: 'Sesc Arcoverde',
        date: '2026-05-22',
        time: '20:00',
        status: 'confirmed',
        coords: { lat: -8.4189, lng: -37.0539 },
        distanceFromPreviousKm: 118,
        travelTime: '2h10',
      },
      {
        id: 'stop-recife',
        municipalityId: 'recife',
        municipality: 'Recife',
        venue: 'Teatro Marco Camarotti',
        date: '2026-05-24',
        time: '18:00',
        status: 'pending',
        coords: { lat: -8.0476, lng: -34.877 },
        distanceFromPreviousKm: 256,
        travelTime: '4h05',
      },
      {
        id: 'stop-olinda',
        municipalityId: 'olinda',
        municipality: 'Olinda',
        venue: 'Mercado Eufrásio Barbosa',
        date: '2026-05-26',
        time: '17:00',
        status: 'confirmed',
        coords: { lat: -8.0089, lng: -34.8553 },
        distanceFromPreviousKm: 8,
        travelTime: '25min',
      },
    ],
  },
  {
    id: 'circuito-corpos-sertao',
    name: 'Corpos do Agreste ao Alto Sertão',
    status: 'PLANNING',
    region: 'Agreste',
    showId: 'corpos-barro',
    showName: 'Corpos de Barro',
    group: 'Cia Trapiá de Dança',
    startDate: '2026-06-12',
    endDate: '2026-06-15',
    contractors: ['Sesc Caruaru', 'Sesc Garanhuns'],
    totalCost: 28600,
    confirmedStops: 2,
    costShares: [
      { contractor: 'Sesc Caruaru', value: 15000, color: '#D4A017' },
      { contractor: 'Sesc Garanhuns', value: 13600, color: '#B85C38' },
    ],
    stops: [
      {
        id: 'stop-caruaru-danca',
        municipalityId: 'caruaru',
        municipality: 'Caruaru',
        venue: 'Teatro Difusora',
        date: '2026-06-12',
        time: '20:00',
        status: 'confirmed',
        coords: { lat: -8.2846, lng: -35.9699 },
      },
      {
        id: 'stop-garanhuns-danca',
        municipalityId: 'garanhuns',
        municipality: 'Garanhuns',
        venue: 'Sesc Garanhuns',
        date: '2026-06-14',
        time: '19:00',
        status: 'pending',
        coords: { lat: -8.882, lng: -36.4966 },
        distanceFromPreviousKm: 103,
        travelTime: '1h50',
      },
    ],
  },
]

export const opportunities: CircuitOpportunity[] = [
  {
    id: 'opp-mata-circo',
    region: 'Zona da Mata',
    showName: 'Lonas Abertas',
    group: 'Coletivo Circo na Mata',
    municipalities: ['Goiana', 'Palmares', 'Vitória de Santo Antão'],
    period: '20 a 24 de junho',
    estimatedSavings: 37,
    unitsInterested: 3,
  },
  {
    id: 'opp-sertao-musica',
    region: 'Sertão do São Francisco',
    showName: 'Rio de Dentro',
    group: 'Núcleo São Francisco de Música',
    municipalities: ['Petrolina', 'Ouricuri', 'Salgueiro', 'Serra Talhada'],
    period: 'primeira semana de julho',
    estimatedSavings: 42,
    unitsInterested: 4,
  },
  {
    id: 'opp-escolas',
    region: 'Agreste',
    showName: 'Corpos de Barro',
    group: 'Cia Trapiá de Dança',
    municipalities: ['Caruaru', 'Garanhuns', 'Arcoverde'],
    period: '12 a 15 de junho',
    estimatedSavings: 29,
    unitsInterested: 3,
  },
]

export const resources: Resource[] = [
  {
    id: 'res-pa-recife',
    name: 'PA 24 canais + operador',
    type: 'Som',
    city: 'Recife',
    region: 'Recife',
    owner: 'Sesc Casa Amarela',
    availability: 'available',
    networkShared: true,
    rating: 4.9,
    coords: { lat: -8.0476, lng: -34.877 },
  },
  {
    id: 'res-van-caruaru',
    name: 'Van de carga 8m³',
    type: 'Transporte',
    city: 'Caruaru',
    region: 'Agreste',
    owner: 'Transporte Borborema',
    availability: 'by_schedule',
    pricePerDay: 720,
    networkShared: false,
    coords: { lat: -8.2846, lng: -35.9699 },
  },
  {
    id: 'res-tec-arcoverde',
    name: 'Técnico de luz cênica',
    type: 'Técnicos',
    city: 'Arcoverde',
    region: 'Sertão',
    owner: 'Lia Produções',
    availability: 'available',
    pricePerDay: 450,
    networkShared: false,
    rating: 4.8,
    coords: { lat: -8.4189, lng: -37.0539 },
  },
  {
    id: 'res-hotel-petrolina',
    name: 'Hospedagem rede parceira',
    type: 'Hospedagem',
    city: 'Petrolina',
    region: 'Sertão do São Francisco',
    owner: 'Pousada Beira Rio',
    availability: 'busy',
    pricePerDay: 180,
    networkShared: false,
    coords: { lat: -9.3891, lng: -40.5027 },
  },
  {
    id: 'res-palco-caruaru',
    name: 'Palco desmontável 8×6m',
    type: 'Palco',
    city: 'Caruaru',
    region: 'Agreste',
    owner: 'Sesc Caruaru',
    availability: 'available',
    networkShared: true,
    rating: 4.6,
    coords: { lat: -8.2846, lng: -35.9699 },
  },
  {
    id: 'res-tec-garanhuns',
    name: 'Operador de som e luz',
    type: 'Técnicos',
    city: 'Garanhuns',
    region: 'Agreste',
    owner: 'Fernanda Almeida',
    availability: 'by_schedule',
    pricePerDay: 380,
    networkShared: false,
    rating: 4.5,
    coords: { lat: -8.882, lng: -36.4966 },
  },
  {
    id: 'res-grupo-olinda',
    name: 'Grupo Maracatu Nação Estrela',
    type: 'Grupos Locais',
    city: 'Olinda',
    region: 'Grande Recife',
    owner: 'Mestre Zé Duda',
    availability: 'available',
    networkShared: false,
    rating: 5.0,
    coords: { lat: -8.0089, lng: -34.8553 },
  },
  {
    id: 'res-produtor-serra-talhada',
    name: 'Produtor cultural local',
    type: 'Produtores',
    city: 'Serra Talhada',
    region: 'Sertão',
    owner: 'Marcos Régis Produções',
    availability: 'available',
    pricePerDay: 320,
    networkShared: false,
    rating: 4.7,
    coords: { lat: -7.9919, lng: -38.2988 },
  },
  {
    id: 'res-hospedagem-caruaru',
    name: 'Hospedagem coletiva (8 pessoas)',
    type: 'Hospedagem',
    city: 'Caruaru',
    region: 'Agreste',
    owner: 'Casa de Cultura do Povo',
    availability: 'available',
    pricePerDay: 90,
    networkShared: true,
    rating: 4.3,
    coords: { lat: -8.2846, lng: -35.9699 },
  },
  {
    id: 'res-espaco-palmares',
    name: 'Centro Cultural dos Palmares',
    type: 'Espaços',
    city: 'Palmares',
    region: 'Zona da Mata',
    owner: 'Prefeitura de Palmares',
    availability: 'available',
    networkShared: true,
    coords: { lat: -8.6842, lng: -35.589 },
  },
]

export const schools: School[] = [
  {
    id: 'esc-floresta',
    name: 'Escola Três Marias',
    city: 'Floresta',
    region: 'Sertão',
    students: 420,
    ageRange: '8 a 15 anos',
    interests: ['Teatro', 'Cultura Popular'],
    structures: ['Pátio coberto', 'Sala ampla'],
    neverServed: true,
  },
  {
    id: 'esc-palmares',
    name: 'Escola Monsenhor Abílio',
    city: 'Palmares',
    region: 'Zona da Mata',
    students: 610,
    ageRange: '6 a 14 anos',
    interests: ['Circo', 'Música'],
    structures: ['Auditório 120 lugares'],
    neverServed: true,
  },
  {
    id: 'esc-caruaru',
    name: 'Escola Mestre Vitalino',
    city: 'Caruaru',
    region: 'Agreste',
    students: 760,
    ageRange: '10 a 17 anos',
    interests: ['Dança', 'Mamulengo'],
    structures: ['Quadra coberta', 'Auditório 180 lugares'],
    neverServed: false,
    lastVisitMonths: 4,
  },
]

export const regionMetrics: RegionMetric[] = [
  { region: 'Recife', presentations: 38, pulse: 88, schools: 19 },
  { region: 'Grande Recife', presentations: 24, pulse: 72, schools: 13 },
  { region: 'Zona da Mata', presentations: 9, pulse: 31, schools: 7 },
  { region: 'Agreste', presentations: 29, pulse: 69, schools: 18 },
  { region: 'Sertão', presentations: 12, pulse: 28, schools: 9 },
  { region: 'Sertão do São Francisco', presentations: 11, pulse: 43, schools: 8 },
]

export const pulseEvolution: PulseEvolution[] = [
  { month: 'Jan', Recife: 78, Agreste: 44, Sertão: 18, 'Zona da Mata': 22 },
  { month: 'Fev', Recife: 80, Agreste: 49, Sertão: 21, 'Zona da Mata': 25 },
  { month: 'Mar', Recife: 82, Agreste: 53, Sertão: 24, 'Zona da Mata': 28 },
  { month: 'Abr', Recife: 85, Agreste: 61, Sertão: 26, 'Zona da Mata': 30 },
  { month: 'Mai', Recife: 88, Agreste: 69, Sertão: 28, 'Zona da Mata': 31 },
]
