import type { Municipality } from '../types/map.types'

export const municipalities: Municipality[] = [
  {
    id: 'recife',
    name: 'Recife',
    region: 'Recife',
    coords: { lat: -8.0476, lng: -34.877 },
    population: 1488920,
    pulseIndex: 92,
    status: 'pulse',
    daysSinceLastEvent: 0,
    activeCircuits: ['circuito-mamulengo'],
    venues: ['Teatro Marco Camarotti', 'Armazém do Campo Cultural'],
    resources: ['PA 24 canais', 'Técnicos de luz', 'Van executiva'],
    schools: 68,
    lastEvents: [
      { date: '2026-05-21', title: 'A Peleja do Riso', language: 'Mamulengo' },
      { date: '2026-05-14', title: 'Mar de Dentro', language: 'Dança' },
    ],
  },
  {
    id: 'olinda',
    name: 'Olinda',
    region: 'Grande Recife',
    coords: { lat: -8.0089, lng: -34.8553 },
    population: 349976,
    pulseIndex: 78,
    status: 'high',
    daysSinceLastEvent: 4,
    activeCircuits: ['circuito-mamulengo'],
    venues: ['Mercado Eufrásio Barbosa', 'Casa Estação da Luz'],
    resources: ['Palco modular', 'Hospedagem parceira'],
    schools: 24,
    lastEvents: [{ date: '2026-05-17', title: 'Brincadeira de Mestre', language: 'Cultura Popular' }],
  },
  {
    id: 'caruaru',
    name: 'Caruaru',
    region: 'Agreste',
    coords: { lat: -8.2846, lng: -35.9699 },
    population: 378052,
    pulseIndex: 82,
    status: 'pulse',
    daysSinceLastEvent: 1,
    activeCircuits: ['circuito-mamulengo', 'circuito-corpos-sertao'],
    venues: ['Sesc Caruaru', 'Teatro Difusora'],
    resources: ['Técnico de som', 'Micro-ônibus', 'Refletores LED'],
    schools: 36,
    lastEvents: [{ date: '2026-05-20', title: 'O Boi no Terreiro', language: 'Teatro' }],
  },
  {
    id: 'garanhuns',
    name: 'Garanhuns',
    region: 'Agreste',
    coords: { lat: -8.882, lng: -36.4966 },
    population: 142506,
    pulseIndex: 64,
    status: 'medium',
    daysSinceLastEvent: 15,
    activeCircuits: ['circuito-corpos-sertao'],
    venues: ['Centro Cultural Alfredo Leite', 'Sesc Garanhuns'],
    resources: ['Hospedagem rede', 'Van de carga'],
    schools: 18,
    lastEvents: [{ date: '2026-05-06', title: 'Corpos de Barro', language: 'Dança' }],
  },
  {
    id: 'arcoverde',
    name: 'Arcoverde',
    region: 'Sertão',
    coords: { lat: -8.4189, lng: -37.0539 },
    population: 77654,
    pulseIndex: 71,
    status: 'high',
    daysSinceLastEvent: 6,
    activeCircuits: ['circuito-mamulengo'],
    venues: ['Sesc Arcoverde', 'Cine Rio Branco'],
    resources: ['Bonecos e oficina', 'Técnico local'],
    schools: 15,
    lastEvents: [{ date: '2026-05-15', title: 'O Riso da Mala', language: 'Mamulengo' }],
  },
  {
    id: 'petrolina',
    name: 'Petrolina',
    region: 'Sertão do São Francisco',
    coords: { lat: -9.3891, lng: -40.5027 },
    population: 386786,
    pulseIndex: 59,
    status: 'medium',
    daysSinceLastEvent: 19,
    activeCircuits: [],
    venues: ['Sesc Petrolina', 'Teatro Dona Amélia'],
    resources: ['Hotel parceiro', 'Som médio porte'],
    schools: 31,
    lastEvents: [{ date: '2026-05-02', title: 'Rio que Dança', language: 'Dança' }],
  },
  {
    id: 'salgueiro',
    name: 'Salgueiro',
    region: 'Sertão',
    coords: { lat: -8.0742, lng: -39.1191 },
    population: 62652,
    pulseIndex: 28,
    status: 'low',
    daysSinceLastEvent: 42,
    activeCircuits: [],
    venues: ['Auditório Municipal', 'Escola Pais e Mestres'],
    resources: ['Gerador pequeno'],
    schools: 13,
    lastEvents: [{ date: '2026-04-09', title: 'Vozes do Couro', language: 'Música' }],
  },
  {
    id: 'serra-talhada',
    name: 'Serra Talhada',
    region: 'Sertão',
    coords: { lat: -7.9919, lng: -38.2988 },
    population: 92769,
    pulseIndex: 35,
    status: 'low',
    daysSinceLastEvent: 38,
    activeCircuits: [],
    venues: ['Estação do Forró', 'Sesc Serra Talhada'],
    resources: ['Palco praça', 'Técnica de produção'],
    schools: 16,
    lastEvents: [{ date: '2026-04-13', title: 'Cantoria Urbana', language: 'Música' }],
  },
  {
    id: 'goiana',
    name: 'Goiana',
    region: 'Zona da Mata',
    coords: { lat: -7.5606, lng: -34.9959 },
    population: 80683,
    pulseIndex: 24,
    status: 'low',
    daysSinceLastEvent: 51,
    activeCircuits: [],
    venues: ['Cine Teatro Polytheama', 'Pátio Cultural'],
    resources: ['Transporte regional'],
    schools: 12,
    lastEvents: [{ date: '2026-03-31', title: 'Mata em Cena', language: 'Teatro' }],
  },
  {
    id: 'palmares',
    name: 'Palmares',
    region: 'Zona da Mata',
    coords: { lat: -8.6842, lng: -35.589 },
    population: 63700,
    pulseIndex: 18,
    status: 'off',
    daysSinceLastEvent: 76,
    activeCircuits: [],
    venues: ['Centro Cultural dos Palmares'],
    resources: ['Auditório escola'],
    schools: 11,
    lastEvents: [{ date: '2026-03-06', title: 'Cena de Rua', language: 'Circo' }],
  },
  {
    id: 'ouricuri',
    name: 'Ouricuri',
    region: 'Sertão',
    coords: { lat: -7.8825, lng: -40.0817 },
    population: 70466,
    pulseIndex: 12,
    status: 'off',
    daysSinceLastEvent: 91,
    activeCircuits: [],
    venues: ['Quadra Cultural Municipal'],
    resources: ['Hospedagem simples'],
    schools: 9,
    lastEvents: [{ date: '2026-02-20', title: 'Ciranda no Sertão', language: 'Cultura Popular' }],
  },
  {
    id: 'floresta',
    name: 'Floresta',
    region: 'Sertão',
    coords: { lat: -8.6013, lng: -38.5687 },
    population: 33642,
    pulseIndex: 8,
    status: 'off',
    daysSinceLastEvent: 114,
    activeCircuits: [],
    venues: ['Escola Três Marias', 'Praça da Matriz'],
    resources: ['Nenhum recurso técnico mapeado'],
    schools: 7,
    lastEvents: [{ date: '2026-01-27', title: 'Aula espetáculo de reisado', language: 'Cultura Popular' }],
  },
]

export const PERNAMBUCO_CENTER: [number, number] = [-8.8828, -36.4967]
export const PERNAMBUCO_BOUNDS: [[number, number], [number, number]] = [
  [-10.2, -41.5],
  [-7.1, -34.4],
]
